=== IfA/PAMTraM/casestudies/de.mfreund.pamtram.casestudies.ctt-aminolight/metamodel/ctt.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema xmlns="http://giove.isti.cnr.it/ctt"
   elementFormDefault="qualified" targetNamespace="http://giove.isti.cnr.it/ctt"
   xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="TaskModel">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="Task" type="Task" />
         </xs:sequence>
         <xs:attribute name="NameTaskModelID" type="xs:string"
            use="required" />
      </xs:complexType>
   </xs:element>

   <xs:complexType name="Task">
      <xs:sequence>
         <xs:element name="Name" type="xs:string" />
         <xs:element name="Type" type="xs:string" />
         <xs:element minOccurs="0" name="Description" type="xs:string" />
         <xs:element minOccurs="0" maxOccurs="unbounded" name="Platform"
            type="xs:string" />
         <xs:element minOccurs="0" name="Precondition" type="ConditionGroup" />
         <xs:element minOccurs="0" name="Postcondition" type="ConditionGroup"/>
         <xs:element minOccurs="0" maxOccurs="1" name="TemporalOperator"
            type="TemporalOperator" />
         <xs:element minOccurs="0" name="TimePerformance" type="TimePerformance" />
         <xs:element minOccurs="0" maxOccurs="1" name="Parent"
            type="Parent" />
         <xs:element minOccurs="0" maxOccurs="1" name="SiblingLeft"
            type="SiblingLeft" />
         <xs:element minOccurs="0" maxOccurs="1" name="SiblingRight"
            type="SiblingRight" />
         <xs:element minOccurs="0" maxOccurs="unbounded" name="Object"
            type="Object" />
         <xs:element minOccurs="0" maxOccurs="1" name="SubTask"
            type="SubTask" />
      </xs:sequence>
      <xs:attribute name="Identifier" type="xs:string" use="required" />
      <xs:attribute name="Category" use="required" type="Category" />
      <xs:attribute name="Iterative" use="required" type="xs:boolean" />
      <xs:attribute name="Optional" use="required" type="xs:boolean" />
      <xs:attribute name="PartOfCooperation" use="required"
         type="xs:boolean" />
      <xs:attribute name="Frequency" type="xs:string" use="required" />
   </xs:complexType>



   <xs:complexType name="TemporalOperator">
      <xs:attribute name="name" type="TemporalOperatorName" />
   </xs:complexType>

   <xs:complexType name="TimePerformance">
      <xs:sequence>
         <xs:element name="Max" type="xs:string" />
         <xs:element name="Min" type="xs:string" />
         <xs:element name="Average" type="xs:string" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="Parent">
      <xs:attribute name="name" type="xs:string" use="required" />
   </xs:complexType>

   <xs:complexType name="SiblingLeft">
      <xs:attribute name="name" type="xs:string" use="required" />
   </xs:complexType>

   <xs:complexType name="SiblingRight">
      <xs:attribute name="name" type="xs:string" use="required" />
   </xs:complexType>

   <xs:complexType name="Object">
      <xs:sequence>
         <xs:element minOccurs="0" maxOccurs="unbounded" name="Platform"
            type="xs:string" />
         <xs:element minOccurs="0" name="InputAction" type="InputAction" />
         <xs:element minOccurs="0" name="OutputAction" type="OutputAction" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="class" use="required" type="ObjectClass" />
      <xs:attribute name="type"  type="ObjectType" />
      <xs:attribute name="access_mode"  type="ObjectAccess" />
      <xs:attribute name="cardinality"  type="ObjectCardinality" />
   </xs:complexType>

   <xs:complexType name="InputAction">
      <xs:attribute name="Description" type="xs:string" use="required" />
      <xs:attribute name="From" type="xs:string" use="required" />
   </xs:complexType>

   <xs:complexType name="OutputAction">
      <xs:attribute name="Description" type="xs:string" use="required" />
      <xs:attribute name="To" type="xs:string" use="required" />
   </xs:complexType>

   <xs:complexType name="SubTask">
      <xs:sequence>
         <xs:element minOccurs="1" maxOccurs="unbounded" name="Task" type="Task" />
      </xs:sequence>
   </xs:complexType>


   <!-- structured precondition modeling -->

   <xs:complexType name="ConditionGroup">
      <xs:choice minOccurs="1" maxOccurs="unbounded">
         <xs:element name="ConditionGroup" type="ConditionGroup" />
         <xs:element name="ConditionLiteral" type="ConditionLiteral" />
      </xs:choice>
      <xs:attribute name="operator" type="BinaryOperator" />
   </xs:complexType>

   <xs:complexType name="ConditionLiteral">
      <xs:attribute name="object" type="xs:string" />
      <xs:attribute name="value" type="xs:string" />
   </xs:complexType>

   <!-- Simple types -->
   <xs:simpleType name="Category">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="abstraction" />
         <xs:enumeration value="user" />
         <xs:enumeration value="interaction" />
         <xs:enumeration value="application" />
         <xs:enumeration value="cooperation" />
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="TemporalOperatorName">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="SequentialEnabling" />
         <xs:enumeration value="Disabling" />
         <xs:enumeration value="Choice" />
         <xs:enumeration value="Interleaving" />
         <xs:enumeration value="InterleavingInfo" />
         <xs:enumeration value="Synchronization" />
         <xs:enumeration value="SuspendResume" />
         <xs:enumeration value="SequentialEnablingInfo" />
         <xs:enumeration value="OrderIndependence"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="ObjectClass">
      <xs:restriction base="xs:NMTOKEN">
      	<xs:enumeration value="Boolean" />
      	<xs:enumeration value="Date" />
      	<xs:enumeration value="Decimal" />
      	<xs:enumeration value="Integer" />
      	<xs:enumeration value="String" />
      	<xs:enumeration value="Time" />
         <xs:enumeration value="Text" />
         <xs:enumeration value="Numerical" />
         <xs:enumeration value="Object" />
         <xs:enumeration value="Description" />
         <xs:enumeration value="Position" />
         <xs:enumeration value="null" />
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="ObjectType">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="Perceivable" />
         <xs:enumeration value="Application" />
         <xs:enumeration value="null" />
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="ObjectAccess">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="Access" />
         <xs:enumeration value="Modification" />
         <xs:enumeration value="null" />
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="ObjectCardinality">
      <xs:restriction base="xs:NMTOKEN">
         <xs:enumeration value="Low" />
         <xs:enumeration value="Medium" />
         <xs:enumeration value="High" />
         <xs:enumeration value="null" />
      </xs:restriction>
   </xs:simpleType>


   <xs:simpleType name="BinaryOperator">
      <xs:restriction base="xs:string">
         <xs:enumeration value="and" id="and" />
         <xs:enumeration value="or" id="or" />
         <xs:enumeration value="xor" id="xor" />
         <xs:enumeration value="contains" id="contains" />
         <xs:enumeration value="starts" id="starts" />
         <xs:enumeration value="ends" id="ends" />
         <xs:enumeration value="gt" id="gt" />
         <xs:enumeration value="gteq" id="gteq" />
         <xs:enumeration value="lteq" id="lteq" />
         <xs:enumeration value="lt" id="lt" />
         <xs:enumeration value="eq" id="eq" />
         <xs:enumeration value="neq" id="neq" />
      </xs:restriction>
   </xs:simpleType>

</xs:schema>

=== IfA/PAMTraM/casestudies/de.mfreund.pamtram.casestudies.ctt-aminolight/Source/distanceMeassurement.xml
<?xmp version="1.0" encoding="UTF-8" standalone="yes"?>
<TaskModel xmlns="http://giove.isti.cnr.it/ctt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://giove.isti.cnr.it/ctt ctt.xsd" NameTaskModelID="FAS">
    <Task Identifier="FAS" Category="abstraction" Iterative="false" Optional="false" PartOfCooperation="false" Frequency=" ">
        <Name>FAS</Name>
        <Type>None</Type>
        <Object name="distance" class="Numerical"/>
        <Object name="velocity" class="Numerical"/>
        <Object name="velocity2" class="Numerical"/>
        <SubTask>
            <Task Identifier="distanceMeassurement" Category="application" Iterative="false" Optional="false" PartOfCooperation="false" Frequency=" ">
                <Name>distanceMeassurement</Name>
                <Type>Feedback</Type>
                <TemporalOperator name="Choice"/>
                <Parent name="FAS"/>
                <SubTask>
                    <Task Identifier="giveFeedback" Category="application" Iterative="false" Optional="false" PartOfCooperation="false" Frequency=" ">
                        <Name>giveFeedback</Name>
                        <Type>Feedback</Type>
                        <TemporalOperator name="Synchronization"/>
                        <Parent name="distanceMeassurement"/>
                        <SiblingRight name="meassureDistance"/>
                        <SubTask>
                            <Task Identifier="parkMode" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
<Name>parkMode</Name>
<Type>Feedback</Type>
<Precondition operator="and">
    <ConditionGroup operator="lteq">
        <ConditionLiteral object="velocity"/>
        <ConditionLiteral value="15"/>
    </ConditionGroup>
</Precondition>
<Postcondition operator="and">
    <ConditionGroup operator="gt">
        <ConditionLiteral object="velocity"/>
        <ConditionLiteral value="15"/>
    </ConditionGroup>    
</Postcondition>
<TemporalOperator name="OrderIndependence"/>
<Parent name="giveFeedback"/>
<SiblingRight name="ACCMode"/>
<Object name="velocity" class="Numerical"/>
<Object name="velocity2" class="Numerical"/>
<SubTask>
    <Task Identifier="noDanger" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>noDanger</Name>
        <Type>Alarm0</Type>
        <Precondition operator="and">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="12"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="and">
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="12"/>
            </ConditionGroup>
        </Postcondition>
        <TemporalOperator name="OrderIndependence"/>
        <Parent name="parkMode"/>
        <SiblingRight name="lowDanger"/>
        <Object name="distance" class="Numerical"/>
    </Task>
    <Task Identifier="lowDanger" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>lowDanger</Name>
        <Type>Alarm1</Type>
        <Precondition operator="and">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="8"/>
            </ConditionGroup>
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="12"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="or">
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="8"/>
            </ConditionGroup>
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="12"/>
            </ConditionGroup>
        </Postcondition>
        <TemporalOperator name="OrderIndependence"/>
        <Parent name="parkMode"/>
        <SiblingLeft name="noDanger"/>
        <SiblingRight name="mediumDanger"/>
        <Object name="distance" class="Numerical"/>
    </Task>
    <Task Identifier="mediumDanger" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>mediumDanger</Name>
        <Type>Alarm2</Type>
        <Precondition operator="and">
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="8"/>
            </ConditionGroup>
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="3"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="or">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="8"/>
            </ConditionGroup>
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="3"/>
            </ConditionGroup>
        </Postcondition>
        <TemporalOperator name="OrderIndependence"/>
        <Parent name="parkMode"/>
        <SiblingLeft name="lowDanger"/>
        <SiblingRight name="highDanger"/>
        <Object name="distance" class="Numerical"/>
    </Task>
    <Task Identifier="highDanger" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>highDanger</Name>
        <Type>Alarm3</Type>
        <Precondition operator="and">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="0.2"/>
            </ConditionGroup>
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="3"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="or">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="3"/>
            </ConditionGroup>
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="0.2"/>
            </ConditionGroup>
        </Postcondition>
        <TemporalOperator name="OrderIndependence"/>
        <Parent name="parkMode"/>
        <SiblingLeft name="mediumDanger"/>
        <SiblingRight name="collision"/>
        <Object name="distance" class="Numerical"/>
    </Task>
    <Task Identifier="collision" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>collision</Name>
        <Type>Alarm4</Type>
        <Precondition operator="and">
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="0.2"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="and">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="0.2"/>
            </ConditionGroup>
        </Postcondition>
        <Parent name="parkMode"/>
        <SiblingLeft name="highDanger"/>
        <Object name="distance" class="Numerical"/>
    </Task>
</SubTask>
                            </Task>
                            <Task Identifier="ACCMode" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
<Name>ACCMode</Name>
<Type>Feedback</Type>
<Precondition operator="and">
    <ConditionGroup operator="gt">
        <ConditionLiteral object="velocity"/>
        <ConditionLiteral value="15"/>
    </ConditionGroup>
</Precondition>
<Postcondition operator="and">
    <ConditionGroup operator="lteq">
        <ConditionLiteral object="velocity"/>
        <ConditionLiteral value="15"/>
    </ConditionGroup>
</Postcondition>
<Parent name="giveFeedback"/>
<SiblingLeft name="parkMode"/>
<Object name="velocity" class="Numerical"/>
<SubTask>
    <Task Identifier="noDanger" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>noDanger</Name>
        <Type>Alarm0</Type>
        <Precondition operator="and">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="120"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="and">
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="120"/>
            </ConditionGroup>
        </Postcondition>
        <TemporalOperator name="OrderIndependence"/>
        <Parent name="ACCMode"/>
        <SiblingRight name="lowDanger"/>
        <Object name="distance" class="Numerical"/>
    </Task>
    <Task Identifier="lowDanger" Category="application" Iterative="true" Optional="true" PartOfCooperation="false" Frequency=" ">
        <Name>lowDanger</Name>
        <Type>Alarm1</Type>
        <Precondition operator="and">
            <ConditionGroup operator="lteq">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="120"/>
            </ConditionGroup>
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="80"/>
            </ConditionGroup>
        </Precondition>
        <Postcondition operator="or">
            <ConditionGroup operator="gt">
                <ConditionLiteral object="distance"/>
                <ConditionLiteral value="120"/>
